[build]
  publish = "/build"  # Vite build output directory
  command = "npm run build"  # The build command
  base="/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
